### ISSUE TITLE
Failed to transform file 'hand_tracking_aar.aar' to match attributes {artifactType=android-compiled-dependencies-resources}

### ISSUE THREAD

**Issue by DionNam** [zhouzaihang/flutter_hand_tracking_plugin#1]
Hi. First of all, thanks for sharing good open-source.
I have cloned your repository, and tried to run the example on my local machine.
But when I tried to run it, I got errors like below.

********************************Error code***********************************

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform file 'hand_tracking_aar.aar' to match attributes {artifactType=android-compiled-dependencies-resources}
      > Execution failed for AarResourcesCompilerTransform: /home/daehyeon/.gradle/caches/transforms-2/files-2.1/f288be8ddaa4d301a851bc5959afacdc/jetified-hand_tracking_aar.
         > /home/daehyeon/.gradle/caches/transforms-2/files-2.1/f288be8ddaa4d301a851bc5959afacdc/jetified-hand_tracking_aar/AndroidManifest.xml

********************************Error code***********************************

Since I have only experience with flutter but not aar, I do not know how to fix this error.
Do I need to follow your description from first to the end to run this package?
Thanks in advance.
![rsz_screenshot_from_2020-05-03_23-02-41](https://user-images.githubusercontent.com/40844251/80916411-6dcbc080-8d93-11ea-8cbe-401d58c4fb25.png)

**Comment by zhouzaihang** [comment]
hi, Glad to help you.
You can try to check if the file  'hand_tracking_aar.aar'  exists in the
path(flutter_hand_tracking_plugin/android/libs/hand_tracking_aar.aar)
https://github.com/zhouzaihang/flutter_hand_tracking_plugin/blob/master/android/libs/hand_tracking_aar.aar

Because it stored in git lfs. Git Large File Storage (LFS) replaces large
files such as ('hand_tracking_aar.aar') with text pointers inside Git,
while storing the file contents on a remote server like GitHub.com or
GitHub Enterprise.

If it does not exist, or exists as a link, you need to install `git lfs`
to get it.You also could downloaded the .aar file into the path, and then
rebuild the project.

Daehyeon <notifications@github.com> 于2020年5月3日周日 下午10:11写道：

**Comment by sid1270** [comment]
Hey @zhouzaihang I tried building my own aar file and was sucessful but even after copying into libs folder I have the same issue. Can you send me the aar file too? Thanks in advance. 
Email: siddhant.shivdikar@gmail.com
